name: Deploy Frontend

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: self-hosted # ← utiliser ton runner self-hosted
    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 3️⃣ Build et déploiement
      - name: Build & Deploy Frontend
        run: |
          cd /home/safidy/mnp-webmapping/frontend
          git fetch
          git reset --hard origin/main
          pnpm install
          pnpm run build
          pm2 reload webmap-frontend
          echo "Frontend déployé avec succès ! 🚀"
